Repository DD2480-Group-27/assignment2-CI, pull requests merged in 2025-02, with the labels that each got.

#5 feat: Main folder structure
  .gitignore
  resources/.gitkeep
  src/Main.java
  src/code_verification/.gitkeep
  src/server_communication/.gitkeep
  test/MainTest.java
  test/code_verification/.gitkeep
  test/server_communication/.gitkeep
Labels: enhancement

#9 Edgar/feat/folder structure for maven
  .gitignore
  pom.xml
  src/main/java/Main.java
  src/main/java/code_verification/.gitkeep
  src/main/java/code_verification/code_verification/.gitkeep
  src/main/java/server_communication/.gitkeep
  src/main/java/server_communication/server_communication/.gitkeep
  src/test/java/MainTest.java
  src/test/java/code_verification/.gitkeep
  src/test/java/server_communication/.gitkeep
Labels: refactoring

#10 Edgar/feat/folder structure JUnit change (solves #4)
  pom.xml
  src/test/java/MainTest.java
Labels: refactoring

#17 Linus/feat/add CI server (Closes #1, closes #3)
  pom.xml
  src/main/java/CIServer.java
  src/main/java/Main.java
  src/test/java/CIServerTest.java
Labels: enhancement, refactoring

#21 Added test & fixed a bug in cloneRepo
  pom.xml
  resources/WebhookJSONAnalyserTestSample.json
  resources/server_setup.sh
  src/main/java/CIServer.java
  src/main/java/server_communication/WebhookJSONAnalyser.java
  src/test/java/CIServerTest.java
  src/test/java/server_communication/WebhookJSONAnalyserTest.java
Labels: enhancement

#8 Edgar/feat/syntax check test execution
  resources/dd2480-builds.zip
  resources/setup-codeVerifTestRes-linux.sh
  src/main/java/CIServer.java
  src/main/java/code_verification/CodeVerifier.java
  src/main/java/code_verification/code_verification/.gitkeep
  src/main/java/server_communication/server_communication/.gitkeep
  src/test/java/CIServerTest.java
  src/test/java/MainTest.java
  src/test/java/code_verification/CodeVerifierTest.java
Labels: enhancement

#22 Kristin/feat/send email (Closes #18)
  pom.xml
  src/main/java/server_communication/Email.java
Labels: enhancement

#32 Kristin/feat/call email Closes #26 Closes #24
  README.md
  pom.xml
  resources/dd2480-builds.zip
  src/main/java/CIServer.java
  src/main/java/server_communication/Email.java
Labels: enhancement

#28 doc: Maven html documentation generating library (closes #27)
  README.md
  doc/apidocs/CIServer.html
  doc/apidocs/allclasses-index.html
  doc/apidocs/allpackages-index.html
  doc/apidocs/class-use/CIServer.html
  doc/apidocs/code_verification/CodeVerifier.html
  doc/apidocs/code_verification/class-use/CodeVerifier.html
  doc/apidocs/code_verification/package-summary.html
  doc/apidocs/code_verification/package-tree.html
  doc/apidocs/code_verification/package-use.html
  doc/apidocs/copy.svg
  doc/apidocs/element-list
  doc/apidocs/index-all.html
  doc/apidocs/index.html
  doc/apidocs/legal/COPYRIGHT
  doc/apidocs/legal/LICENSE
  doc/apidocs/legal/jquery.md
  doc/apidocs/legal/jqueryUI.md
  doc/apidocs/link.svg
  doc/apidocs/member-search-index.js
  doc/apidocs/module-search-index.js
  doc/apidocs/overview-summary.html
  doc/apidocs/overview-tree.html
  doc/apidocs/package-search-index.js
  doc/apidocs/package-summary.html
  doc/apidocs/package-tree.html
  doc/apidocs/package-use.html
  doc/apidocs/resources/glass.png
  doc/apidocs/resources/x.png
  doc/apidocs/script-dir/jquery-3.7.1.min.js
  doc/apidocs/script-dir/jquery-ui.min.css
  doc/apidocs/script-dir/jquery-ui.min.js
  doc/apidocs/script.js
  doc/apidocs/search-page.js
  doc/apidocs/search.html
  doc/apidocs/search.js
  doc/apidocs/server_communication/Email.html
  doc/apidocs/server_communication/WebhookJSONAnalyser.html
  doc/apidocs/server_communication/class-use/Email.html
  doc/apidocs/server_communication/class-use/WebhookJSONAnalyser.html
  doc/apidocs/server_communication/package-summary.html
  doc/apidocs/server_communication/package-tree.html
  doc/apidocs/server_communication/package-use.html
  doc/apidocs/stylesheet.css
  doc/apidocs/tag-search-index.js
  doc/apidocs/type-search-index.js
  pom.xml
  resources/CI_cover.jpg
  src/main/java/CIServer.java
  src/main/java/code_verification/CodeVerifier.java
  src/main/java/server_communication/Email.java
  src/main/java/server_communication/WebhookJSONAnalyser.java
  src/test/java/code_verification/CodeVerifierTest.java
Labels: documentation
